# Generated by Django 6.0 on 2025-12-12 09:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_us_person', models.BooleanField(default=False, help_text='ITAR compliance: Is this user a US Person (citizen/permanent resident)?')),
                ('security_clearance_level', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret')], default='UNCLASSIFIED', help_text="User's security clearance level", max_length=20)),
                ('organization', models.CharField(blank=True, help_text='Company or organization name', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.IntegerField(help_text='User ID who performed action')),
                ('actor_username', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload')], max_length=20)),
                ('resource_type', models.CharField(help_text='Model name', max_length=50)),
                ('resource_id', models.UUIDField(help_text='Object UUID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Before/after values for updates')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor_id', 'timestamp'], name='audit_logs_actor_i_ce2144_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx')],
            },
        ),
        migrations.CreateModel(
            name='DesignAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (prevents enumeration attacks)', primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='Sequential version number (1, 2, 3...)', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When geometry processing completed', null=True)),
                ('filename', models.CharField(help_text="Original filename (e.g., 'bracket_v2.step')", max_length=255)),
                ('s3_key', models.CharField(help_text='Full S3 path: designs/{uuid}/{filename}', max_length=512, unique=True)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash for integrity verification', max_length=64)),
                ('classification', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('ITAR', 'ITAR Controlled'), ('EAR99', 'Export Administration Regulations'), ('CUI', 'Controlled Unclassified Information')], db_index=True, default='UNCLASSIFIED', help_text='Export control classification', max_length=20)),
                ('status', models.CharField(choices=[('UPLOADING', 'Upload in Progress'), ('PROCESSING', 'Processing Geometry'), ('COMPLETED', 'Processing Complete'), ('FAILED', 'Processing Failed')], db_index=True, default='UPLOADING', help_text='Current processing status', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extracted physical properties: volume, surface_area, center_of_mass, etc.')),
                ('is_valid_geometry', models.BooleanField(help_text='Passed Design Rule Checks (manifold, watertight, etc.)', null=True)),
                ('validation_report', models.JSONField(blank=True, default=dict, help_text='Detailed validation results')),
                ('units', models.CharField(default='millimeters', help_text='Native units of the CAD file', max_length=20)),
                ('revision', models.CharField(blank=True, help_text="Revision label (e.g., 'Rev A', 'v2.1')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this version')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Search tags: ['aerospace', 'bracket', 'critical']")),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this design', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Design Asset',
                'verbose_name_plural': 'Design Assets',
                'db_table': 'design_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyNode',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Component name', max_length=255)),
                ('part_number', models.CharField(blank=True, help_text='Part number', max_length=100)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity in assembly')),
                ('reference_designator', models.CharField(blank=True, help_text="Reference designator (e.g., 'R1', 'C23')", max_length=50)),
                ('node_type', models.CharField(choices=[('ASSEMBLY', 'Assembly'), ('SUBASSEMBLY', 'Sub-Assembly'), ('PART', 'Part'), ('HARDWARE', 'Commercial Hardware')], default='PART', max_length=20)),
                ('mass', models.FloatField(blank=True, help_text='Mass in kilograms', null=True)),
                ('volume', models.FloatField(blank=True, help_text='Volume in cubic mm', null=True)),
                ('component_metadata', models.JSONField(blank=True, default=dict, help_text='Additional part data (material, finish, supplier, cost, etc.)')),
                ('design_asset', models.ForeignKey(help_text='Parent design this BOM belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bom_nodes', to='designs.designasset')),
            ],
            options={
                'verbose_name': 'BOM Node',
                'verbose_name_plural': 'BOM Nodes',
                'db_table': 'assembly_nodes',
            },
        ),
        migrations.CreateModel(
            name='DesignSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.CharField(db_index=True, help_text="Stable part number across all versions (e.g., 'TB-001', 'BRK-42-A')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this part/assembly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_series_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Design Series',
                'verbose_name_plural': 'Design Series',
                'db_table': 'design_series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='designasset',
            name='series',
            field=models.ForeignKey(help_text='Parent series (part number) this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='designs.designseries'),
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active Review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_created', to=settings.AUTH_USER_MODEL)),
                ('design_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to='designs.designasset')),
                ('reviewers', models.ManyToManyField(help_text='Engineers assigned to review this design', related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Session',
                'verbose_name_plural': 'Review Sessions',
                'db_table': 'review_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('anchor_point', models.JSONField(help_text='3D coordinate: {x, y, z}')),
                ('camera_state', models.JSONField(help_text='Camera position and target: {position: {x,y,z}, target: {x,y,z}, up: {x,y,z}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Has this comment been addressed?')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markups_created', to=settings.AUTH_USER_MODEL)),
                ('review_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markups', to='designs.reviewsession')),
            ],
            options={
                'verbose_name': 'Markup',
                'verbose_name_plural': 'Markups',
                'db_table': 'markups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('HASH_CALCULATION', 'Hash Calculation'), ('GEOMETRY_EXTRACTION', 'Geometry Extraction'), ('BOM_PARSING', 'BOM Parsing'), ('VALIDATION', 'Validation Check'), ('INTERFERENCE_CHECK', 'Interference Check'), ('MASS_PROPERTIES', 'Mass Properties Calculation')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRY', 'Retrying')], default='PENDING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='Celery task UUID for tracking', max_length=255)),
                ('result', models.JSONField(blank=True, default=dict, help_text='Job output data')),
                ('error_message', models.TextField(blank=True, help_text='Error details if job failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('design_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='designs.designasset')),
            ],
            options={
                'verbose_name': 'Analysis Job',
                'verbose_name_plural': 'Analysis Jobs',
                'db_table': 'analysis_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'job_type'], name='analysis_jo_status_7f3199_idx'), models.Index(fields=['celery_task_id'], name='analysis_jo_celery__d60842_idx'), models.Index(fields=['design_asset', '-created_at'], name='analysis_jo_design__456d1c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='designasset',
            index=models.Index(fields=['classification', 'status'], name='design_asse_classif_ab361b_idx'),
        ),
        migrations.AddIndex(
            model_name='designasset',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='design_asse_uploade_fd610d_idx'),
        ),
        migrations.AddIndex(
            model_name='designasset',
            index=models.Index(fields=['file_hash'], name='design_asse_file_ha_856264_idx'),
        ),
        migrations.AddIndex(
            model_name='designasset',
            index=models.Index(fields=['series', '-version_number'], name='design_asse_series__eb49f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='designasset',
            constraint=models.UniqueConstraint(fields=('series', 'version_number'), name='unique_version_per_series'),
        ),
    ]
