# Generated by Django 6.0 on 2025-12-10 23:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_us_person', models.BooleanField(default=False, help_text='ITAR compliance: Is this user a US Person (citizen/permanent resident)?')),
                ('security_clearance_level', models.CharField(choices=[('NONE', 'No Clearance'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret')], default='NONE', help_text="User's security clearance level", max_length=20)),
                ('organization', models.CharField(blank=True, help_text='Company or organization name', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DesignAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (prevents enumeration attacks)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(help_text="Original filename (e.g., 'bracket_v2.step')", max_length=255)),
                ('s3_key', models.CharField(help_text='Full S3 path: designs/{uuid}/{filename}', max_length=512, unique=True)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(help_text='SHA-256 hash for integrity verification', max_length=64, unique=True)),
                ('classification', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('ITAR', 'ITAR Controlled'), ('EAR99', 'Export Administration Regulations'), ('CUI', 'Controlled Unclassified Information')], db_index=True, default='UNCLASSIFIED', help_text='Export control classification', max_length=20)),
                ('status', models.CharField(choices=[('UPLOADING', 'Upload in Progress'), ('PROCESSING', 'Processing Geometry'), ('COMPLETED', 'Processing Complete'), ('FAILED', 'Processing Failed')], db_index=True, default='UPLOADING', help_text='Current processing status', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extracted physical properties: volume, surface_area, center_of_mass, etc.')),
                ('is_valid_geometry', models.BooleanField(help_text='Passed Design Rule Checks (manifold, watertight, etc.)', null=True)),
                ('validation_report', models.JSONField(blank=True, default=dict, help_text='Detailed validation results')),
                ('units', models.CharField(default='millimeters', help_text='Native units of the CAD file', max_length=20)),
                ('part_number', models.CharField(blank=True, db_index=True, help_text="Engineering part number (e.g., 'BRK-001-A')", max_length=100)),
                ('revision', models.CharField(blank=True, help_text="Revision or version (e.g., 'Rev A', 'v2.1')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Human-readable description')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Search tags: ['aerospace', 'bracket', 'critical']")),
                ('created_by', models.ForeignKey(help_text='User who uploaded this design', on_delete=django.db.models.deletion.PROTECT, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Design Asset',
                'verbose_name_plural': 'Design Assets',
                'db_table': 'design_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='Component name', max_length=255)),
                ('part_number', models.CharField(blank=True, help_text='Part number', max_length=100)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity in assembly')),
                ('reference_designator', models.CharField(blank=True, help_text="Reference designator (e.g., 'R1', 'C23')", max_length=50)),
                ('node_type', models.CharField(choices=[('ASSEMBLY', 'Assembly'), ('SUBASSEMBLY', 'Sub-Assembly'), ('PART', 'Part'), ('HARDWARE', 'Commercial Hardware')], default='PART', max_length=20)),
                ('mass', models.FloatField(blank=True, help_text='Mass in kilograms', null=True)),
                ('volume', models.FloatField(blank=True, help_text='Volume in cubic mm', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional part data (material, finish, supplier, cost, etc.)')),
                ('design_asset', models.ForeignKey(help_text='Parent design this BOM belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bom_nodes', to='designs.designasset')),
            ],
            options={
                'verbose_name': 'BOM Node',
                'verbose_name_plural': 'BOM Nodes',
                'db_table': 'assembly_nodes',
            },
        ),
        migrations.AddIndex(
            model_name='designasset',
            index=models.Index(fields=['classification', 'status'], name='design_asse_classif_ab361b_idx'),
        ),
        migrations.AddIndex(
            model_name='designasset',
            index=models.Index(fields=['created_by', 'created_at'], name='design_asse_created_ad8987_idx'),
        ),
        migrations.AddIndex(
            model_name='designasset',
            index=models.Index(fields=['file_hash'], name='design_asse_file_ha_856264_idx'),
        ),
    ]
