# Generated by Django 6.0 on 2025-12-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designasset',
            name='units',
            field=models.CharField(choices=[('mm', 'Millimeters'), ('cm', 'Centimeters'), ('m', 'Meters'), ('km', 'Kilometers'), ('um', 'Micrometers (Microns)'), ('nm', 'Nanometers'), ('in', 'Inches'), ('ft', 'Feet'), ('yd', 'Yards'), ('mi', 'Miles')], default='mm', help_text='Native units of the CAD file', max_length=2),
        ),
    ]
