# Generated by Django 6.0 on 2025-12-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_alter_designasset_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designasset',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hash for integrity verification', max_length=64),
        ),
        migrations.AlterField(
            model_name='designasset',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='designasset',
            name='s3_key',
            field=models.CharField(blank=True, help_text='Full S3 path: designs/{uuid}/{filename}', max_length=512, null=True, unique=True),
        ),
    ]
