# Generated by Django 6.0 on 2025-12-16 07:53

import designs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_alter_designasset_file_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designasset',
            name='file',
            field=models.FileField(blank=True, help_text='Actual CAD file (STEP/IGES)', max_length=512, null=True, upload_to=designs.models.DesignAsset.upload_to_path),
        ),
    ]
