# Generated by Django 6.0 on 2025-12-16 08:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_designasset_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer'), ('GUEST', 'Guest')], default='MEMBER', help_text="User's role in this organization", max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
                'db_table': 'organization_memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AlterField(
            model_name='designseries',
            name='part_number',
            field=models.CharField(db_index=True, help_text="Stable part number across all versions (e.g., 'TB-001', 'BRK-42-A')", max_length=100),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='design_asset',
            field=models.ForeignKey(help_text='Design being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to='designs.designasset'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Organization name (e.g., 'Acme Engineering', 'DoD Customer')", max_length=255)),
                ('slug', models.SlugField(help_text="URL-safe unique identifier (e.g., 'acme-engineering')", max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Only lowercase letters, numbers, and hyphens allowed', regex='^[a-z0-9-]+$')])),
                ('description', models.TextField(blank=True, help_text='Optional description of the organization')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to prevent access without deleting data')),
                ('is_us_organization', models.BooleanField(default=True, help_text='Is this a US-based organization? (ITAR compliance)')),
                ('max_users', models.PositiveIntegerField(default=50, help_text='Maximum number of users allowed in this organization')),
                ('max_storage_gb', models.PositiveIntegerField(default=100, help_text='Maximum storage quota in GB')),
                ('subscription_tier', models.CharField(choices=[('FREE', 'Free Tier'), ('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='STARTER', help_text='Subscription tier (determines features and limits)', max_length=20)),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email for organization', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_bdc355_idx')],
            },
        ),
        migrations.AddField(
            model_name='designseries',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this design series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_series', to='designs.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='designseries',
            unique_together={('organization', 'part_number')},
        ),
        migrations.AddIndex(
            model_name='designseries',
            index=models.Index(fields=['organization', 'part_number'], name='design_seri_organiz_def3ae_idx'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='designs.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role'], name='organizatio_organiz_25ae86_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user'], name='organizatio_user_id_db5190_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('organization', 'user')},
        ),
    ]
