# Generated by Django 6.0 on 2025-12-16 08:22

from django.db import migrations


def create_default_organization(apps, schema_editor):
    """Create default organization and assign existing data to it."""
    Organization = apps.get_model('designs', 'Organization')
    DesignSeries = apps.get_model('designs', 'DesignSeries')
    CustomUser = apps.get_model('designs', 'CustomUser')
    OrganizationMembership = apps.get_model('designs', 'OrganizationMembership')
    
    # Create default organization
    default_org, created = Organization.objects.get_or_create(
        slug='default',
        defaults={
            'name': 'Default Organization',
            'description': 'Default organization for existing data',
            'is_active': True,
            'is_us_organization': True,
            'max_users': 100,
            'max_storage_gb': 1000,
            'subscription_tier': 'ENTERPRISE',
        }
    )
    
    if created:
        print(f"Created default organization: {default_org}")
    
    # Assign all existing DesignSeries to default organization
    design_series_count = DesignSeries.objects.filter(organization__isnull=True).update(
        organization=default_org
    )
    print(f"Assigned {design_series_count} design series to default organization")
    
    # Create organization memberships for all existing users
    users = CustomUser.objects.all()
    memberships_created = 0
    for user in users:
        membership, created = OrganizationMembership.objects.get_or_create(
            organization=default_org,
            user=user,
            defaults={'role': 'ADMIN'}  # Make all existing users admins
        )
        if created:
            memberships_created += 1
    
    print(f"Created {memberships_created} organization memberships")


def reverse_migration(apps, schema_editor):
    """Remove default organization."""
    Organization = apps.get_model('designs', 'Organization')
    Organization.objects.filter(slug='default').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_add_multi_tenant_organizations'),
    ]

    operations = [
        migrations.RunPython(create_default_organization, reverse_migration),
    ]
