# Generated by Django 6.0 on 2025-12-16 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0007_apikey_refreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_enabled', models.BooleanField(default=True, help_text='Master switch for all email notifications')),
                ('notify_design_uploaded', models.BooleanField(default=True, help_text='Notify when a new design is uploaded to a series I follow')),
                ('notify_design_approved', models.BooleanField(default=True, help_text='Notify when my design is approved')),
                ('notify_design_rejected', models.BooleanField(default=True, help_text='Notify when my design is rejected')),
                ('notify_review_started', models.BooleanField(default=True, help_text='Notify when a review session is started on my design')),
                ('notify_review_completed', models.BooleanField(default=True, help_text='Notify when a review session is completed')),
                ('notify_markup_added', models.BooleanField(default=True, help_text='Notify when someone adds a markup to my design')),
                ('notify_job_completed', models.BooleanField(default=True, help_text='Notify when background processing job completes')),
                ('notify_job_failed', models.BooleanField(default=True, help_text='Notify when background processing job fails')),
                ('notify_organization_invite', models.BooleanField(default=True, help_text='Notify when invited to join an organization')),
                ('notify_role_changed', models.BooleanField(default=True, help_text='Notify when my role in an organization changes')),
                ('delivery_method', models.CharField(choices=[('IMMEDIATE', 'Immediate - Send emails immediately'), ('HOURLY', 'Hourly Digest - Bundle notifications hourly'), ('DAILY', 'Daily Digest - Send one email per day'), ('WEEKLY', 'Weekly Digest - Send one email per week')], default='IMMEDIATE', help_text='How to deliver email notifications', max_length=20)),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Enable quiet hours (no notifications during specified times)')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (e.g., 22:00)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours (e.g., 08:00)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('DESIGN_UPLOADED', 'Design Uploaded'), ('DESIGN_APPROVED', 'Design Approved'), ('DESIGN_REJECTED', 'Design Rejected'), ('REVIEW_STARTED', 'Review Started'), ('REVIEW_COMPLETED', 'Review Completed'), ('MARKUP_ADDED', 'Markup Added'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_FAILED', 'Job Failed'), ('ORGANIZATION_INVITE', 'Organization Invite'), ('ROLE_CHANGED', 'Role Changed'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('SECURITY_ALERT', 'Security Alert')], db_index=True, help_text='Type of notification', max_length=50)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('message_plain', models.TextField(help_text='Plain text email body')),
                ('message_html', models.TextField(blank=True, help_text='HTML email body (optional)')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context for email template')),
                ('status', models.CharField(choices=[('PENDING', 'Pending - Waiting to send'), ('QUEUED', 'Queued - In delivery queue'), ('SENDING', 'Sending - Currently being sent'), ('SENT', 'Sent - Successfully delivered'), ('FAILED', 'Failed - Delivery failed'), ('CANCELLED', 'Cancelled - User or system cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=10)),
                ('rate_limit_key', models.CharField(blank=True, db_index=True, help_text="Key for rate limiting (e.g., 'user:<id>:hour')", max_length=255)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
                'db_table': 'email_notifications',
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='email_notif_recipie_504841_idx'), models.Index(fields=['status', 'priority', 'queued_at'], name='email_notif_status_93a978_idx'), models.Index(fields=['notification_type', 'queued_at'], name='email_notif_notific_4400f4_idx'), models.Index(fields=['next_retry_at'], name='email_notif_next_re_37d626_idx')],
            },
        ),
    ]
