# Generated by Django 6.0 on 2025-12-16 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0008_notificationpreference_emailnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name for this validation rule', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Description of what this rule validates')),
                ('rule_type', models.CharField(choices=[('REGEX', 'Regular Expression'), ('RANGE', 'Numeric Range'), ('LENGTH', 'String Length'), ('FORMAT', 'Format Validation'), ('CUSTOM', 'Custom Python Expression'), ('FILE_TYPE', 'File Type Validation'), ('FILE_SIZE', 'File Size Validation'), ('UNIQUENESS', 'Uniqueness Check'), ('RELATIONSHIP', 'Relationship Validation'), ('BUSINESS_RULE', 'Business Logic Rule')], help_text='Type of validation to perform', max_length=20)),
                ('target_model', models.CharField(choices=[('DesignAsset', 'Design Asset'), ('DesignSeries', 'Design Series'), ('Organization', 'Organization'), ('CustomUser', 'User'), ('ReviewSession', 'Review Session'), ('Markup', 'Markup'), ('AssemblyNode', 'Assembly Node'), ('*', 'All Models')], help_text='Model this rule applies to', max_length=50)),
                ('target_field', models.CharField(blank=True, help_text='Specific field to validate (leave blank for model-level validation)', max_length=100)),
                ('rule_config', models.JSONField(default=dict, help_text='Configuration for the rule (regex pattern, min/max values, etc.)')),
                ('error_message', models.CharField(help_text='Error message to display when validation fails', max_length=500)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='ERROR', help_text='Severity level of validation failure', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('apply_on_create', models.BooleanField(default=True, help_text='Apply validation when creating new records')),
                ('apply_on_update', models.BooleanField(default=True, help_text='Apply validation when updating existing records')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditional logic for when to apply this rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_checks', models.PositiveIntegerField(default=0, help_text='Total number of times this rule has been checked')),
                ('total_failures', models.PositiveIntegerField(default=0, help_text='Total number of validation failures')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_validation_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='If set, rule only applies to this organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='designs.organization')),
            ],
            options={
                'verbose_name': 'Validation Rule',
                'verbose_name_plural': 'Validation Rules',
                'db_table': 'validation_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_model', models.CharField(help_text='Model that was validated', max_length=50)),
                ('target_id', models.UUIDField(help_text='ID of the record that was validated')),
                ('target_field', models.CharField(blank=True, help_text='Specific field that was validated', max_length=100)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('ERROR', 'Validation Error')], help_text='Outcome of the validation', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if validation failed')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed validation results and context')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('was_blocked', models.BooleanField(default=False, help_text='Whether the operation was blocked due to validation failure')),
                ('was_overridden', models.BooleanField(default=False, help_text='Whether validation failure was overridden by user')),
                ('override_reason', models.TextField(blank=True, help_text='Reason for overriding validation failure')),
                ('override_at', models.DateTimeField(blank=True, help_text='When validation was overridden', null=True)),
                ('override_by', models.ForeignKey(blank=True, help_text='User who overrode the validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_overrides', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, help_text='User who triggered the validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_results', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(help_text='Validation rule that was applied', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='designs.validationrule')),
            ],
            options={
                'verbose_name': 'Validation Result',
                'verbose_name_plural': 'Validation Results',
                'db_table': 'validation_results',
                'ordering': ['-validated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='validationrule',
            index=models.Index(fields=['target_model', 'target_field'], name='validation__target__408b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrule',
            index=models.Index(fields=['is_active'], name='validation__is_acti_02c9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrule',
            index=models.Index(fields=['organization'], name='validation__organiz_865160_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['target_model', 'target_id'], name='validation__target__74813e_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['status'], name='validation__status_fd9378_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['validated_at'], name='validation__validat_27fc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['was_blocked'], name='validation__was_blo_c63030_idx'),
        ),
    ]
