# Generated by Django 6.0 on 2025-12-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0009_validation_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='organizatio_slug_5b8b37_idx',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='organizatio_is_acti_bdc355_idx',
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='organizationmembership',
            name='organizatio_organiz_25ae86_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationmembership',
            name='organizatio_user_id_db5190_idx',
        ),
        migrations.RemoveIndex(
            model_name='designseries',
            name='design_seri_organiz_def3ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='validationrule',
            name='validation__organiz_865160_idx',
        ),
        migrations.AlterUniqueTogether(
            name='designseries',
            unique_together={('part_number',)},
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='notify_organization_invite',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='notify_role_changed',
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='notification_type',
            field=models.CharField(choices=[('DESIGN_UPLOADED', 'Design Uploaded'), ('DESIGN_APPROVED', 'Design Approved'), ('DESIGN_REJECTED', 'Design Rejected'), ('REVIEW_STARTED', 'Review Started'), ('REVIEW_COMPLETED', 'Review Completed'), ('MARKUP_ADDED', 'Markup Added'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_FAILED', 'Job Failed'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('SECURITY_ALERT', 'Security Alert')], db_index=True, help_text='Type of notification', max_length=50),
        ),
        migrations.AlterField(
            model_name='validationrule',
            name='target_model',
            field=models.CharField(choices=[('DesignAsset', 'Design Asset'), ('DesignSeries', 'Design Series'), ('CustomUser', 'User'), ('ReviewSession', 'Review Session'), ('Markup', 'Markup'), ('AssemblyNode', 'Assembly Node'), ('*', 'All Models')], help_text='Model this rule applies to', max_length=50),
        ),
        migrations.AddIndex(
            model_name='designseries',
            index=models.Index(fields=['part_number'], name='design_seri_part_nu_9413d9_idx'),
        ),
        migrations.RemoveField(
            model_name='validationrule',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='designseries',
            name='organization',
        ),
        migrations.DeleteModel(
            name='OrganizationMembership',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
