# Generated by Django 6.0 on 2025-12-17 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0010_remove_organization_organizatio_slug_5b8b37_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('DESIGN_UPLOADED', 'Design Uploaded'), ('DESIGN_APPROVED', 'Design Approved'), ('DESIGN_REJECTED', 'Design Rejected'), ('DESIGN_UPDATED', 'Design Updated'), ('REVIEW_ASSIGNED', 'Review Assigned'), ('REVIEW_STARTED', 'Review Started'), ('REVIEW_COMPLETED', 'Review Completed'), ('REVIEW_COMMENT', 'Review Comment Added'), ('MARKUP_ADDED', 'Markup Added'), ('MARKUP_RESOLVED', 'Markup Resolved'), ('MENTION', 'Mentioned in Comment'), ('VALIDATION_FAILED', 'Validation Failed'), ('VALIDATION_PASSED', 'Validation Passed'), ('JOB_COMPLETED', 'Processing Job Completed'), ('JOB_FAILED', 'Processing Job Failed'), ('SYSTEM_ALERT', 'System Alert'), ('SECURITY_ALERT', 'Security Alert')], db_index=True, help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title/headline', max_length=255)),
                ('message', models.TextField(help_text='Notification message body')),
                ('resource_type', models.CharField(blank=True, help_text='Type of related resource (e.g., DesignAsset, ReviewSession)', max_length=50)),
                ('resource_id', models.UUIDField(blank=True, help_text='ID of related resource', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Has the user read this notification?')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Has the user archived this notification?')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='When the notification was archived', null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', help_text='Notification priority level', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When this notification expires (optional)', null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_06c470_idx'), models.Index(fields=['recipient', 'is_archived', 'created_at'], name='notificatio_recipie_aa94fc_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_4b40ec_idx'), models.Index(fields=['resource_type', 'resource_id'], name='notificatio_resourc_32703e_idx')],
            },
        ),
    ]
